[package]
name = "stasko_calculator_parser"
version = "1.1.2"
edition = "2024"
license = "MIT"
description = "Парсер для обробки складних математичних виразів"

[dependencies]
anyhow = "1.0.100"
pest = "2.8.3"
pest_derive = "2.8.3"
thiserror = "1.0.61"
